# Generated by Django 4.1.3 on 2023-01-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='boarding',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='days2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hourse2',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hourse3',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hourse4',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hourse5',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='never6',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='yes',
        ),
    ]
